name: CI

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
  merge_group:

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
# env:
#  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
#  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build-lint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: default
          POSTGRES_PASSWORD: default
          POSTGRES_DB: verceldb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy env
        run: |
          cp .env.example .env.local
          echo "POSTGRES_URL=postgresql://postgres:postgres@localhost:5432/postgres" >> .env.local
          echo "NEXTAUTH_SECRET=your-nextauth-secret-key-here-min-32-chars" >> .env.local
          echo "GITHUB_CLIENT_ID=github_client_id_placeholder" >> .env.local
          echo "GITHUB_CLIENT_SECRET=github_client_secret_placeholder" >> .env.local
          echo "STRIPE_API_KEY=sk_test_stripe_api_key_placeholder" >> .env.local
          echo "STRIPE_WEBHOOK_SECRET=whsec_stripe_webhook_secret_placeholder" >> .env.local
          echo "NEXT_PUBLIC_POSTHOG_KEY=phc_posthog_key_placeholder" >> .env.local
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=" >> .env.local
          echo "CLERK_SECRET_KEY=" >> .env.local

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install lib
        run: bun i

      - name: Build
        run: bun run build
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: localhost
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          POSTGRES_USER: default
          POSTGRES_PASSWORD: default
          POSTGRES_DB: verceldb
          POSTGRES_URL: postgres://default:default@localhost:5432/verceldb
          # Skip database connection during build
          SKIP_DB_CONNECTION: true


      - name: lint and type-check
        run: bun run lint && bun run format && bun run typecheck